site_name: my doc

nav:
  - Home: index.md
  - Python_sample: python_sample.md
  - Calculator: calculator.md
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
