apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python
  annotations:
    backstage.io/techdocs-ref: dir:.
  description: Python docs with mkdocstrings
spec:
  type: documentation
  lifecycle: experimental
  owner: user:guest
